CREATE TRIGGER UPDATE_SL_TANG ON CTPN 
FOR INSERT AS 
BEGIN 
DECLARE @SL INT
DECLARE @MAHH NVARCHAR
DECLARE CONTRO CURSOR FOR SELECT MAHH, SOLUONG FROM INSERTED 
OPEN CONTRO 
FETCH NEXT FROM CONTRO INTO @MAHH, @SL
WHILE @@FETCH_STATUS = 0
BEGIN 
UPDATE HANG_HOA SET SOLUONG = HANG_HOA.SOLUONG + @SL 
FROM INSERTED WHERE HANG_HOA.MAHH = INSERTED.MAHH
FETCH NEXT FROM CONTRO INTO @MAHH, @SL
END
CLOSE CONTRO 
DEALLOCATE CONTRO 
END 

INSERT INTO PHIEU_NHAP(SoPN, NgayPN, MaNCC) 
VALUES('PN5', '2022-09-14', 'NCC2')
INSERT INTO CTPN(SoPN, MaHH, SoLuong, DonGia) 
VALUES('PN5', 'HH4', 18, 100)